"""Reference pricing from actual jobs — edit when your rates change.

Benchmark job: 144 sqft deck — $7,000 material + $7,500 labor = $14,500 (~7 days).
"""

from __future__ import annotations

# Reference deck (your real numbers)
REFERENCE_DECK_SQFT = 144
REFERENCE_MATERIAL_TOTAL = 7_000
REFERENCE_LABOR_TOTAL = 7_500
REFERENCE_CREW_DAYS = 7

MATERIAL_PER_SQFT = REFERENCE_MATERIAL_TOTAL / REFERENCE_DECK_SQFT  # ~48.61
LABOR_PER_SQFT = REFERENCE_LABOR_TOTAL / REFERENCE_DECK_SQFT  # ~52.08
PRICE_PER_SQFT = MATERIAL_PER_SQFT + LABOR_PER_SQFT  # ~100.69

SQFT_PER_CREW_DAY = REFERENCE_DECK_SQFT / REFERENCE_CREW_DAYS  # ~20.6
LABOR_PER_CREW_DAY = LABOR_PER_SQFT * SQFT_PER_CREW_DAY  # ~$1,071/day

MIN_JOB_SIZE = round(REFERENCE_DECK_SQFT * PRICE_PER_SQFT)  # $14,500
TARGET_PROFIT_DAY_MIN = 500
TARGET_PROFIT_DAY_MAX = 1_000
TARGET_PROFIT_DAY = round(LABOR_PER_CREW_DAY)  # ~1,071 from reference job
